baseURL = "https://nimabeh.github.io/"
languageCode = "en-us"
title = "Nima Behravan Port"
disableKinds = ["sitemap", "RSS"]
theme = "."
themesDir = "../"

# uncomment for browsing at file:///
# relativeURLs = true
# uglyURLs = true

[author]
name = "Nima Behravan"

# currently only the unsafe mode for goldmark is supported
[markup.goldmark.renderer]
unsafe = true

# choose between Hugo compile-time or Highlight.js
# syntax highlighting for code inside of code fences
[markup.highlight]
codeFences = false  # use highlight.js 
# codeFences = true  # use hugo highlighting at compile time
style = "tango"  # set a style for hugo highlighting

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true

# used in content/template-example
[params.reveal_hugo.templates.grey]
background = "#368291"
transition = "convex"
